fruits = [{'name': 'Banana', 'id': 1, 'family': 'Musaceae', 'order': 'Zingiberales', 'genus': 'Musa',
           'nutritions': {'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'carbohydrates': 22, 'protein': 1},
           'benefits': ['High in potassium, supports heart health', 'Provides energy, great for pre-workout snack',
                        'Aids digestion due to fiber content']},
          {'name': 'Orange', 'id': 2, 'family': 'Rutaceae', 'order': 'Sapindales', 'genus': 'Citrus',
           'nutritions': {'calories': 43, 'fat': 0.2, 'sugar': 8.2, 'carbohydrates': 8.3, 'protein': 1},
           'benefits': ['Boosts immunity with vitamin C', 'Supports skin health', 'Aids in preventing kidney stones']},
          {'name': 'Strawberry', 'id': 3, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Fragaria',
           'nutritions': {'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'carbohydrates': 5.5, 'protein': 0.8},
           'benefits': ['Rich in vitamin C, boosts immune system',
                        'High in antioxidants, reduces risk of chronic diseases',
                        'Improves heart health by lowering bad cholesterol']},
          {'name': 'Pear', 'id': 4, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Pyrus',
           'nutritions': {'calories': 57, 'fat': 0.1, 'sugar': 10, 'carbohydrates': 15, 'protein': 0.4},
           'benefits': ['Rich in fiber, promotes digestive health', 'Supports heart health by reducing cholesterol',
                        'Contains antioxidants, reduces inflammation']},
          {'name': 'Tomato', 'id': 5, 'family': 'Solanaceae', 'order': 'Solanales', 'genus': 'Solanum',
           'nutritions': {'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'carbohydrates': 3.9, 'protein': 0.9},
           'benefits': ['Rich in lycopene, reduces cancer risk', 'Promotes skin health with vitamin C',
                        'Improves heart health by lowering blood pressure']},
          {'name': 'Apple', 'id': 6, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Malus',
           'nutritions': {'calories': 52, 'fat': 0.4, 'sugar': 10.3, 'carbohydrates': 11.4, 'protein': 0.3},
           'benefits': ['Supports heart health', 'Improves gut health', 'Helps regulate blood sugar levels']},
          {'name': 'Cherry', 'id': 9, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Prunus',
           'nutritions': {'calories': 50, 'fat': 0.3, 'sugar': 8, 'carbohydrates': 12, 'protein': 1},
           'benefits': ['Reduces inflammation', 'Improves sleep quality', 'Supports heart health']},
          {'name': 'Pineapple', 'id': 10, 'family': 'Bromeliaceae', 'order': 'Poales', 'genus': 'Ananas',
           'nutritions': {'calories': 50, 'fat': 0.12, 'sugar': 9.85, 'carbohydrates': 13.12, 'protein': 0.54},
           'benefits': ['Contains bromelain, aids digestion', 'Rich in vitamin C, boosts immune system',
                        'Reduces inflammation and pain']},
          {'name': 'Raspberry', 'id': 23, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Rubus',
           'nutritions': {'calories': 53, 'fat': 0.7, 'sugar': 4.4, 'carbohydrates': 12, 'protein': 1.2},
           'benefits': ['Rich in antioxidants, reducing inflammation', 'Improves blood sugar levels',
                        'Boosts brain function']},
          {'name': 'Watermelon', 'id': 25, 'family': 'Cucurbitaceae', 'order': 'Cucurbitales', 'genus': 'Citrullus',
           'nutritions': {'calories': 30, 'fat': 0.2, 'sugar': 6, 'carbohydrates': 8, 'protein': 0.6},
           'benefits': ['Keeps you hydrated', 'Reduces muscle soreness', 'Supports heart health']},
          {'name': 'Lemon', 'id': 26, 'family': 'Rutaceae', 'order': 'Sapindales', 'genus': 'Citrus',
           'nutritions': {'calories': 29, 'fat': 0.3, 'sugar': 2.5, 'carbohydrates': 9, 'protein': 1.1},
           'benefits': ['Boosts vitamin C levels', 'Aids digestion', 'Improves skin health']},
          {'name': 'Mango', 'id': 27, 'family': 'Anacardiaceae', 'order': 'Sapindales', 'genus': 'Mangifera',
           'nutritions': {'calories': 60, 'fat': 0.38, 'sugar': 13.7, 'carbohydrates': 15, 'protein': 0.82},
           'benefits': ['Boosts immune system', 'Improves digestion', 'Supports eye health']},
          {'name': 'Blueberry', 'id': 33, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Fragaria',
           'nutritions': {'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'carbohydrates': 5.5, 'protein': 0},
           'benefits': ['Supports brain health', 'Reduces risk of heart disease', 'Improves insulin sensitivity']},
          {'name': 'Apricot', 'id': 35, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Prunus',
           'nutritions': {'calories': 15, 'fat': 0.1, 'sugar': 3.2, 'carbohydrates': 3.9, 'protein': 0.5},
           'benefits': ['Promotes eye health', 'Rich in antioxidants', 'Aids in digestion']},
          {'name': 'Guava', 'id': 37, 'family': 'Myrtaceae', 'order': 'Myrtales', 'genus': 'Psidium',
           'nutritions': {'calories': 68, 'fat': 1, 'sugar': 9, 'carbohydrates': 14, 'protein': 2.6},
           'benefits': ['Boosts immunity with vitamin C', 'Improves digestion', 'Supports heart health']},
          {'name': 'Melon', 'id': 41, 'family': 'Cucurbitaceae', 'order': 'Cucurbitaceae', 'genus': 'Cucumis',
           'nutritions': {'calories': 34, 'fat': 0, 'sugar': 8, 'carbohydrates': 8, 'protein': 0},
           'benefits': ['Keeps you hydrated', 'Supports skin health', 'Aids in digestion']},
          {'name': 'Papaya', 'id': 42, 'family': 'Caricaceae', 'order': 'Brassicales', 'genus': 'Carica',
           'nutritions': {'calories': 39, 'fat': 0.3, 'sugar': 4.4, 'carbohydrates': 5.8, 'protein': 0.5},
           'benefits': ['Aids digestion', 'Boosts immunity', 'Promotes skin health']},
          {'name': 'Lime', 'id': 44, 'family': 'Rutaceae', 'order': 'Sapindales', 'genus': 'Citrus',
           'nutritions': {'calories': 25, 'fat': 0.1, 'sugar': 1.7, 'carbohydrates': 8.4, 'protein': 0.3},
           'benefits': ['Boosts immunity', 'Aids digestion', 'Promotes skin health']},
          {'name': 'Persimmon', 'id': 52, 'family': 'Ebenaceae', 'order': 'Rosales', 'genus': 'Diospyros',
           'nutritions': {'calories': 81, 'fat': 0, 'sugar': 18, 'carbohydrates': 18, 'protein': 0},
           'benefits': ['Rich in antioxidants, reduces inflammation', 'Good source of fiber, promotes digestive health',
                        'Boosts immunity due to high vitamin C content']},
          {'name': 'Durian', 'id': 60, 'family': 'Malvaceae', 'order': 'Malvales', 'genus': 'Durio',
           'nutritions': {'calories': 147, 'fat': 5.3, 'sugar': 6.75, 'carbohydrates': 27.1, 'protein': 1.5},
           'benefits': ['Boosts energy due to high calorie content', 'Rich in healthy fats, good for heart health',
                        'Contains fiber, aids digestion']},
          {'name': 'Blackberry', 'id': 64, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Rubus',
           'nutritions': {'calories': 40, 'fat': 0.4, 'sugar': 4.5, 'carbohydrates': 9, 'protein': 1.3},
           'benefits': ['High in antioxidants, reduces oxidative stress', 'Rich in fiber, promotes gut health',
                        'Supports brain health and memory']},
          {'name': 'Kiwi', 'id': 66, 'family': 'Actinidiaceae', 'order': 'Struthioniformes', 'genus': 'Apteryx',
           'nutritions': {'calories': 61, 'fat': 0.5, 'sugar': 9, 'carbohydrates': 15, 'protein': 1.1},
           'benefits': ['High in vitamin C, boosts immune function', 'Aids digestion with fiber and enzymes',
                        'Improves skin health with antioxidants']},
          {'name': 'Lychee', 'id': 67, 'family': 'Sapindaceae', 'order': 'Sapindales', 'genus': 'Litchi',
           'nutritions': {'calories': 66, 'fat': 0.44, 'sugar': 15, 'carbohydrates': 17, 'protein': 0.8},
           'benefits': ['Rich in vitamin C, supports immunity', 'Improves blood circulation',
                        'Promotes skin health with antioxidants']},
          {'name': 'Fig', 'id': 68, 'family': 'Moraceae', 'order': 'Rosales', 'genus': 'Ficus',
           'nutritions': {'calories': 74, 'fat': 0.3, 'sugar': 16, 'carbohydrates': 19, 'protein': 0.8},
           'benefits': ['Improves digestion due to fiber', 'Regulates blood sugar levels',
                        'Supports bone health with calcium']},
          {'name': 'Gooseberry', 'id': 69, 'family': 'Grossulariaceae', 'order': 'Saxifragales', 'genus': 'Ribes',
           'nutritions': {'calories': 44, 'fat': 0.6, 'sugar': 0, 'carbohydrates': 10, 'protein': 0.9},
           'benefits': ['Rich in antioxidants, helping reduce inflammation', 'Supports healthy digestion',
                        'Boosts immunity with vitamin C']},
          {'name': 'Passionfruit', 'id': 70, 'family': 'Passifloraceae', 'order': 'Malpighiales', 'genus': 'Passiflora',
           'nutritions': {'calories': 97, 'fat': 0.7, 'sugar': 11.2, 'carbohydrates': 22.4, 'protein': 2.2},
           'benefits': ['High in fiber, aiding digestion', 'Rich in antioxidants, protecting cells from damage',
                        'Supports heart health by lowering blood pressure']},
          {'name': 'Plum', 'id': 71, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Prunus',
           'nutritions': {'calories': 46, 'fat': 0.28, 'sugar': 9.92, 'carbohydrates': 11.4, 'protein': 0.7},
           'benefits': ['Improves bone health', 'Helps regulate blood sugar levels',
                        'Rich in antioxidants, reducing inflammation']},
          {'name': 'GreenApple', 'id': 72, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Malus',
           'nutritions': {'calories': 21, 'fat': 0.1, 'sugar': 6.4, 'carbohydrates': 3.1, 'protein': 0.4},
           'benefits': ['Promotes weight loss due to low calories', 'Improves gut health with fiber',
                        'Regulates blood sugar levels']},
          {'name': 'Feijoa', 'id': 76, 'family': 'Myrtaceae', 'order': 'Myrtoideae', 'genus': 'Sellowiana',
           'nutritions': {'calories': 44, 'fat': 0.4, 'sugar': 3, 'carbohydrates': 8, 'protein': 0.6},
           'benefits': ['Improves digestion', 'Supports immune function', 'Boosts metabolism']},
          {'name': 'Tangerine', 'id': 77, 'family': 'Rutaceae', 'order': 'Sapindales', 'genus': 'Citrus',
           'nutritions': {'calories': 45, 'fat': 0.4, 'sugar': 9.1, 'carbohydrates': 8.3, 'protein': 0},
           'benefits': ['Boosts immunity', 'Supports skin health', 'Aids in weight management']},
          {'name': 'Pitahaya', 'id': 78, 'family': 'Cactaceae', 'order': 'Caryophyllales', 'genus': 'Cactaceae',
           'nutritions': {'calories': 36, 'fat': 0.4, 'sugar': 3, 'carbohydrates': 7, 'protein': 1},
           'benefits': ['Rich in antioxidants', 'Improves digestion', 'Supports heart health']},
          {'name': 'Pomegranate', 'id': 79, 'family': 'Lythraceae', 'order': 'Myrtales', 'genus': 'Punica',
           'nutritions': {'calories': 83, 'fat': 1.2, 'sugar': 13.7, 'carbohydrates': 18.7, 'protein': 1.7},
           'benefits': ['Rich in antioxidants', 'Improves heart health', 'Supports urinary health']},
          {'name': 'Dragonfruit', 'id': 80, 'family': 'Cactaceae', 'order': 'Caryophyllales', 'genus': 'Selenicereus',
           'nutritions': {'calories': 60, 'fat': 1.5, 'sugar': 8, 'carbohydrates': 9, 'protein': 9},
           'benefits': ['Boosts immunity', 'Improves gut health', 'Supports healthy skin']},
          {'name': 'Grape', 'id': 81, 'family': 'Vitaceae', 'order': 'Vitales', 'genus': 'Vitis',
           'nutritions': {'calories': 69, 'fat': 0.16, 'sugar': 16, 'carbohydrates': 18.1, 'protein': 0.72},
           'benefits': ['Improves heart health', 'Rich in antioxidants', 'Aids brain function']},
          {'name': 'Morus', 'id': 82, 'family': 'Moraceae', 'order': 'Rosales', 'genus': 'Morus',
           'nutritions': {'calories': 43, 'fat': 0.39, 'sugar': 8.1, 'carbohydrates': 9.8, 'protein': 1.44},
           'benefits': ['Boosts immunity', 'Improves digestion', 'Supports heart health']},
          {'name': 'Avocado', 'id': 84, 'family': 'Lauraceae', 'order': 'Laurales', 'genus': 'Persea',
           'nutritions': {'calories': 160, 'fat': 14.66, 'sugar': 0.66, 'carbohydrates': 8.53, 'protein': 2},
           'benefits': ['Supports heart health', 'Improves skin health', 'Aids in weight management']},
          {'name': 'Kiwifruit', 'id': 85, 'family': 'Actinidiaceae', 'order': 'Ericales', 'genus': 'Actinidia',
           'nutritions': {'calories': 61, 'fat': 0.5, 'sugar': 8.9, 'carbohydrates': 14.6, 'protein': 1.14},
           'benefits': ['Boosts immunity', 'Supports digestion', 'Promotes heart health']},
          {'name': 'Peach', 'id': 86, 'family': 'Rosaceae', 'order': 'Rosales', 'genus': 'Prunus',
           'nutritions': {'calories': 39, 'fat': 0.25, 'sugar': 8.4, 'carbohydrates': 9.5, 'protein': 0.9},
           'benefits': ['Aids digestion', 'Supports skin health', 'Rich in vitamins A and C']},
          {'name': 'Cranberry', 'id': 87, 'family': 'Ericaceae', 'order': 'Ericales', 'genus': 'Vaccinium',
           'nutritions': {'calories': 46, 'fat': 0.1, 'sugar': 4, 'carbohydrates': 12.2, 'protein': 0.4},
           'benefits': ['Prevents urinary tract infections', 'Rich in antioxidants', 'Boosts immune system']},
          {'name': 'Jackfruit', 'id': 94, 'family': 'Moraceae', 'order': 'Rosales', 'genus': 'Artocarpus',
           'nutritions': {'calories': 95, 'fat': 0, 'sugar': 19.1, 'carbohydrates': 23.2, 'protein': 1.72},
           'benefits': ['Boosts immunity', 'Improves digestion', 'Provides energy']},
          {'name': 'Horned Melon', 'id': 95, 'family': 'Cucurbitaceae', 'order': 'Cucurbitales', 'genus': 'Cucumis',
           'nutritions': {'calories': 44, 'fat': 1.26, 'sugar': 0.5, 'carbohydrates': 7.56, 'protein': 1.78},
           'benefits': ['Hydrates the body', 'Promotes skin health', 'Rich in antioxidants']},
          {'name': 'Hazelnut', 'id': 96, 'family': 'Betulaceae', 'order': 'Fagales', 'genus': 'Corylus',
           'nutritions': {'calories': 628, 'fat': 61, 'sugar': 4.3, 'carbohydrates': 17, 'protein': 15},
           'benefits': ['Good for heart health', 'Supports brain function', 'Rich in healthy fats']},
          {'name': 'Pomelo', 'id': 98, 'family': 'Rutaceae', 'order': 'Sapindales', 'genus': 'Citrus',
           'nutritions': {'calories': 37, 'fat': 0, 'sugar': 8.5, 'carbohydrates': 9.67, 'protein': 0.82},
           'benefits': ['Boosts immunity', 'Aids digestion', 'Reduces inflammation']},
          {'name': 'Mangosteen', 'id': 99, 'family': 'Clusiaceae', 'order': 'Malpighiales', 'genus': 'Garcinia',
           'nutritions': {'calories': 73, 'fat': 0.58, 'sugar': 16.11, 'carbohydrates': 17.91, 'protein': 0.41},
           'benefits': ['Anti-inflammatory properties', 'Rich in antioxidants', 'Promotes healthy skin']},
          {'name': 'Pumpkin', 'id': 100, 'family': 'Cucurbitaceae', 'order': 'Cucurbitales', 'genus': 'Cucurbita',
           'nutritions': {'calories': 25, 'fat': 0.3, 'sugar': 3.3, 'carbohydrates': 4.6, 'protein': 1.1},
           'benefits': ['Supports eye health', 'Boosts immunity', 'Rich in fiber']},
          {'name': 'Japanese Persimmon', 'id': 101, 'family': 'Ebenaceae', 'order': 'Ericales', 'genus': 'Diospyros',
           'nutritions': {'calories': 70, 'fat': 0.2, 'sugar': 13, 'carbohydrates': 19, 'protein': 0.6},
           'benefits': ['Improves heart health', 'Rich in fiber', 'Helps reduce inflammation']},
          {'name': 'Annona', 'id': 103, 'family': 'Annonaceae', 'order': 'Rosales', 'genus': 'Annonas',
           'nutritions': {'calories': 92, 'fat': 0.29, 'sugar': 3.4, 'carbohydrates': 19.1, 'protein': 1.5},
           'benefits': ['Boosts immunity', 'Improves digestion', 'Rich in antioxidants']},
          {'name': 'Ceylon Gooseberry', 'id': 104, 'family': 'Salicaceae', 'order': 'Malpighiales', 'genus': 'Dovyalis',
           'nutritions': {'calories': 47, 'fat': 0.3, 'sugar': 8.1, 'carbohydrates': 9.6, 'protein': 1.2},
           'benefits': ['Rich in vitamin C', 'Boosts immunity', 'Aids in digestion']}]
